spring.application.name=room-service

server.port=${SERVER_PORT:8084}

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

spring.datasource.url=jdbc:mariadb://localhost:3306/vista-hotel-room-service
spring.datasource.username=root
spring.datasource.password=123456789
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jackson.mapper.accept-case-insensitive-enums=true

spring.cloud.compatibility-verifier.enabled=false

